# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c_peer2peer_netmessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dotaproto import netmessages_pb2 as netmessages__pb2
from dotaproto import networkbasetypes_pb2 as networkbasetypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='c_peer2peer_netmessages.proto',
  package='dota',
  syntax='proto2',
  serialized_pb=_b('\n\x1d\x63_peer2peer_netmessages.proto\x12\x04\x64ota\x1a\x11netmessages.proto\x1a\x16networkbasetypes.proto\" \n\x10\x43P2P_TextMessage\x12\x0c\n\x04text\x18\x01 \x01(\x0c\"+\n\x15\x43Steam_Voice_Encoding\x12\x12\n\nvoice_data\x18\x01 \x01(\x0c\"m\n\nCP2P_Voice\x12#\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x14.dota.CMsgVoiceAudio\x12\x17\n\x0f\x62roadcast_group\x18\x02 \x01(\r\"!\n\rHandler_Flags\x12\x10\n\x0cPlayed_Audio\x10\x01\"0\n\tCP2P_Ping\x12\x11\n\tsend_time\x18\x01 \x02(\x04\x12\x10\n\x08is_reply\x18\x02 \x02(\x08\"\xda\x01\n\x15\x43P2P_VRAvatarPosition\x12<\n\nbody_parts\x18\x01 \x03(\x0b\x32(.dota.CP2P_VRAvatarPosition.COrientation\x12\x0e\n\x06hat_id\x18\x02 \x01(\x05\x12\x10\n\x08scene_id\x18\x03 \x01(\x05\x12\x13\n\x0bworld_scale\x18\x04 \x01(\x05\x1aL\n\x0c\x43Orientation\x12\x1d\n\x03pos\x18\x01 \x01(\x0b\x32\x10.dota.CMsgVector\x12\x1d\n\x03\x61ng\x18\x02 \x01(\x0b\x32\x10.dota.CMsgQAngle\"\x89\x02\n\x19\x43P2P_WatchSynchronization\x12\x11\n\tdemo_tick\x18\x01 \x01(\x05\x12\x0e\n\x06paused\x18\x02 \x01(\x08\x12\x1f\n\x17tv_listen_voice_indices\x18\x03 \x01(\x05\x12\x1b\n\x13\x64ota_spectator_mode\x18\x04 \x01(\x05\x12+\n#dota_spectator_watching_broadcaster\x18\x05 \x01(\x05\x12!\n\x19\x64ota_spectator_hero_index\x18\x06 \x01(\x05\x12 \n\x18\x64ota_spectator_autospeed\x18\x07 \x01(\x05\x12\x19\n\x11\x64ota_replay_speed\x18\x08 \x01(\x05*}\n\x0cP2P_Messages\x12\x14\n\x0fp2p_TextMessage\x10\x80\x02\x12\x0e\n\tp2p_Voice\x10\x81\x02\x12\r\n\x08p2p_Ping\x10\x82\x02\x12\x19\n\x14p2p_VRAvatarPosition\x10\x83\x02\x12\x1d\n\x18p2p_WatchSynchronization\x10\x84\x02\x42\x03\x80\x01\x00')
  ,
  dependencies=[netmessages__pb2.DESCRIPTOR,networkbasetypes__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_P2P_MESSAGES = _descriptor.EnumDescriptor(
  name='P2P_Messages',
  full_name='dota.P2P_Messages',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='p2p_TextMessage', index=0, number=256,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='p2p_Voice', index=1, number=257,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='p2p_Ping', index=2, number=258,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='p2p_VRAvatarPosition', index=3, number=259,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='p2p_WatchSynchronization', index=4, number=260,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=811,
  serialized_end=936,
)
_sym_db.RegisterEnumDescriptor(_P2P_MESSAGES)

P2P_Messages = enum_type_wrapper.EnumTypeWrapper(_P2P_MESSAGES)
p2p_TextMessage = 256
p2p_Voice = 257
p2p_Ping = 258
p2p_VRAvatarPosition = 259
p2p_WatchSynchronization = 260


_CP2P_VOICE_HANDLER_FLAGS = _descriptor.EnumDescriptor(
  name='Handler_Flags',
  full_name='dota.CP2P_Voice.Handler_Flags',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Played_Audio', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=237,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_CP2P_VOICE_HANDLER_FLAGS)


_CP2P_TEXTMESSAGE = _descriptor.Descriptor(
  name='CP2P_TextMessage',
  full_name='dota.CP2P_TextMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='dota.CP2P_TextMessage.text', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=114,
)


_CSTEAM_VOICE_ENCODING = _descriptor.Descriptor(
  name='CSteam_Voice_Encoding',
  full_name='dota.CSteam_Voice_Encoding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='voice_data', full_name='dota.CSteam_Voice_Encoding.voice_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=159,
)


_CP2P_VOICE = _descriptor.Descriptor(
  name='CP2P_Voice',
  full_name='dota.CP2P_Voice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='dota.CP2P_Voice.audio', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='broadcast_group', full_name='dota.CP2P_Voice.broadcast_group', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CP2P_VOICE_HANDLER_FLAGS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=270,
)


_CP2P_PING = _descriptor.Descriptor(
  name='CP2P_Ping',
  full_name='dota.CP2P_Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send_time', full_name='dota.CP2P_Ping.send_time', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_reply', full_name='dota.CP2P_Ping.is_reply', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=320,
)


_CP2P_VRAVATARPOSITION_CORIENTATION = _descriptor.Descriptor(
  name='COrientation',
  full_name='dota.CP2P_VRAvatarPosition.COrientation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='dota.CP2P_VRAvatarPosition.COrientation.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ang', full_name='dota.CP2P_VRAvatarPosition.COrientation.ang', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=541,
)

_CP2P_VRAVATARPOSITION = _descriptor.Descriptor(
  name='CP2P_VRAvatarPosition',
  full_name='dota.CP2P_VRAvatarPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body_parts', full_name='dota.CP2P_VRAvatarPosition.body_parts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hat_id', full_name='dota.CP2P_VRAvatarPosition.hat_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='dota.CP2P_VRAvatarPosition.scene_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='world_scale', full_name='dota.CP2P_VRAvatarPosition.world_scale', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CP2P_VRAVATARPOSITION_CORIENTATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=541,
)


_CP2P_WATCHSYNCHRONIZATION = _descriptor.Descriptor(
  name='CP2P_WatchSynchronization',
  full_name='dota.CP2P_WatchSynchronization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='demo_tick', full_name='dota.CP2P_WatchSynchronization.demo_tick', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paused', full_name='dota.CP2P_WatchSynchronization.paused', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tv_listen_voice_indices', full_name='dota.CP2P_WatchSynchronization.tv_listen_voice_indices', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dota_spectator_mode', full_name='dota.CP2P_WatchSynchronization.dota_spectator_mode', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dota_spectator_watching_broadcaster', full_name='dota.CP2P_WatchSynchronization.dota_spectator_watching_broadcaster', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dota_spectator_hero_index', full_name='dota.CP2P_WatchSynchronization.dota_spectator_hero_index', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dota_spectator_autospeed', full_name='dota.CP2P_WatchSynchronization.dota_spectator_autospeed', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dota_replay_speed', full_name='dota.CP2P_WatchSynchronization.dota_replay_speed', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=809,
)

_CP2P_VOICE.fields_by_name['audio'].message_type = netmessages__pb2._CMSGVOICEAUDIO
_CP2P_VOICE_HANDLER_FLAGS.containing_type = _CP2P_VOICE
_CP2P_VRAVATARPOSITION_CORIENTATION.fields_by_name['pos'].message_type = networkbasetypes__pb2._CMSGVECTOR
_CP2P_VRAVATARPOSITION_CORIENTATION.fields_by_name['ang'].message_type = networkbasetypes__pb2._CMSGQANGLE
_CP2P_VRAVATARPOSITION_CORIENTATION.containing_type = _CP2P_VRAVATARPOSITION
_CP2P_VRAVATARPOSITION.fields_by_name['body_parts'].message_type = _CP2P_VRAVATARPOSITION_CORIENTATION
DESCRIPTOR.message_types_by_name['CP2P_TextMessage'] = _CP2P_TEXTMESSAGE
DESCRIPTOR.message_types_by_name['CSteam_Voice_Encoding'] = _CSTEAM_VOICE_ENCODING
DESCRIPTOR.message_types_by_name['CP2P_Voice'] = _CP2P_VOICE
DESCRIPTOR.message_types_by_name['CP2P_Ping'] = _CP2P_PING
DESCRIPTOR.message_types_by_name['CP2P_VRAvatarPosition'] = _CP2P_VRAVATARPOSITION
DESCRIPTOR.message_types_by_name['CP2P_WatchSynchronization'] = _CP2P_WATCHSYNCHRONIZATION
DESCRIPTOR.enum_types_by_name['P2P_Messages'] = _P2P_MESSAGES

CP2P_TextMessage = _reflection.GeneratedProtocolMessageType('CP2P_TextMessage', (_message.Message,), dict(
  DESCRIPTOR = _CP2P_TEXTMESSAGE,
  __module__ = 'c_peer2peer_netmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CP2P_TextMessage)
  ))
_sym_db.RegisterMessage(CP2P_TextMessage)

CSteam_Voice_Encoding = _reflection.GeneratedProtocolMessageType('CSteam_Voice_Encoding', (_message.Message,), dict(
  DESCRIPTOR = _CSTEAM_VOICE_ENCODING,
  __module__ = 'c_peer2peer_netmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CSteam_Voice_Encoding)
  ))
_sym_db.RegisterMessage(CSteam_Voice_Encoding)

CP2P_Voice = _reflection.GeneratedProtocolMessageType('CP2P_Voice', (_message.Message,), dict(
  DESCRIPTOR = _CP2P_VOICE,
  __module__ = 'c_peer2peer_netmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CP2P_Voice)
  ))
_sym_db.RegisterMessage(CP2P_Voice)

CP2P_Ping = _reflection.GeneratedProtocolMessageType('CP2P_Ping', (_message.Message,), dict(
  DESCRIPTOR = _CP2P_PING,
  __module__ = 'c_peer2peer_netmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CP2P_Ping)
  ))
_sym_db.RegisterMessage(CP2P_Ping)

CP2P_VRAvatarPosition = _reflection.GeneratedProtocolMessageType('CP2P_VRAvatarPosition', (_message.Message,), dict(

  COrientation = _reflection.GeneratedProtocolMessageType('COrientation', (_message.Message,), dict(
    DESCRIPTOR = _CP2P_VRAVATARPOSITION_CORIENTATION,
    __module__ = 'c_peer2peer_netmessages_pb2'
    # @@protoc_insertion_point(class_scope:dota.CP2P_VRAvatarPosition.COrientation)
    ))
  ,
  DESCRIPTOR = _CP2P_VRAVATARPOSITION,
  __module__ = 'c_peer2peer_netmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CP2P_VRAvatarPosition)
  ))
_sym_db.RegisterMessage(CP2P_VRAvatarPosition)
_sym_db.RegisterMessage(CP2P_VRAvatarPosition.COrientation)

CP2P_WatchSynchronization = _reflection.GeneratedProtocolMessageType('CP2P_WatchSynchronization', (_message.Message,), dict(
  DESCRIPTOR = _CP2P_WATCHSYNCHRONIZATION,
  __module__ = 'c_peer2peer_netmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CP2P_WatchSynchronization)
  ))
_sym_db.RegisterMessage(CP2P_WatchSynchronization)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\000'))
# @@protoc_insertion_point(module_scope)
