# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientmessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='clientmessages.proto',
  package='dota',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x63lientmessages.proto\x12\x04\x64ota\">\n\x1a\x43\x43lientMsg_CustomGameEvent\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"Z\n CClientMsg_CustomGameEventBounce\x12\x12\n\nevent_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x14\n\x0cplayer_index\x18\x03 \x01(\x05\"\xa2\x01\n\x18\x43\x43lientMsg_ClientUIEvent\x12;\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x14.dota.EClientUIEvent:\x16\x45\x43lientUIEvent_Invalid\x12\x13\n\x0b\x65nt_ehandle\x18\x02 \x01(\r\x12\x16\n\x0e\x63lient_ehandle\x18\x03 \x01(\r\x12\r\n\x05\x64\x61ta1\x18\x04 \x01(\t\x12\r\n\x05\x64\x61ta2\x18\x05 \x01(\t\">\n+CClientMsg_DevPaletteVisibilityChangedEvent\x12\x0f\n\x07visible\x18\x01 \x01(\x08\"x\n0CClientMsg_WorldUIControllerHasPanelChangedEvent\x12\x11\n\thas_panel\x18\x01 \x01(\x08\x12\x16\n\x0e\x63lient_ehandle\x18\x02 \x01(\r\x12\x19\n\x11literal_hand_type\x18\x03 \x01(\r\"(\n\x17\x43\x43lientMsg_RotateAnchor\x12\r\n\x05\x61ngle\x18\x01 \x01(\x02*\xdb\x01\n\x13\x45\x42\x61seClientMessages\x12\x17\n\x12\x43M_CustomGameEvent\x10\x98\x02\x12\x1d\n\x18\x43M_CustomGameEventBounce\x10\x99\x02\x12\x15\n\x10\x43M_ClientUIEvent\x10\x9a\x02\x12#\n\x1e\x43M_DevPaletteVisibilityChanged\x10\x9b\x02\x12(\n#CM_WorldUIControllerHasPanelChanged\x10\x9c\x02\x12\x14\n\x0f\x43M_RotateAnchor\x10\x9d\x02\x12\x10\n\x0b\x43M_MAX_BASE\x10\xac\x02*n\n\x0e\x45\x43lientUIEvent\x12\x1a\n\x16\x45\x43lientUIEvent_Invalid\x10\x00\x12!\n\x1d\x45\x43lientUIEvent_DialogFinished\x10\x01\x12\x1d\n\x19\x45\x43lientUIEvent_FireOutput\x10\x02\x42\x05H\x01\x80\x01\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EBASECLIENTMESSAGES = _descriptor.EnumDescriptor(
  name='EBaseClientMessages',
  full_name='dota.EBaseClientMessages',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CM_CustomGameEvent', index=0, number=280,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CM_CustomGameEventBounce', index=1, number=281,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CM_ClientUIEvent', index=2, number=282,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CM_DevPaletteVisibilityChanged', index=3, number=283,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CM_WorldUIControllerHasPanelChanged', index=4, number=284,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CM_RotateAnchor', index=5, number=285,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CM_MAX_BASE', index=6, number=300,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=580,
  serialized_end=799,
)
_sym_db.RegisterEnumDescriptor(_EBASECLIENTMESSAGES)

EBaseClientMessages = enum_type_wrapper.EnumTypeWrapper(_EBASECLIENTMESSAGES)
_ECLIENTUIEVENT = _descriptor.EnumDescriptor(
  name='EClientUIEvent',
  full_name='dota.EClientUIEvent',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EClientUIEvent_Invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EClientUIEvent_DialogFinished', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EClientUIEvent_FireOutput', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=801,
  serialized_end=911,
)
_sym_db.RegisterEnumDescriptor(_ECLIENTUIEVENT)

EClientUIEvent = enum_type_wrapper.EnumTypeWrapper(_ECLIENTUIEVENT)
CM_CustomGameEvent = 280
CM_CustomGameEventBounce = 281
CM_ClientUIEvent = 282
CM_DevPaletteVisibilityChanged = 283
CM_WorldUIControllerHasPanelChanged = 284
CM_RotateAnchor = 285
CM_MAX_BASE = 300
EClientUIEvent_Invalid = 0
EClientUIEvent_DialogFinished = 1
EClientUIEvent_FireOutput = 2



_CCLIENTMSG_CUSTOMGAMEEVENT = _descriptor.Descriptor(
  name='CClientMsg_CustomGameEvent',
  full_name='dota.CClientMsg_CustomGameEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_name', full_name='dota.CClientMsg_CustomGameEvent.event_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='dota.CClientMsg_CustomGameEvent.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=92,
)


_CCLIENTMSG_CUSTOMGAMEEVENTBOUNCE = _descriptor.Descriptor(
  name='CClientMsg_CustomGameEventBounce',
  full_name='dota.CClientMsg_CustomGameEventBounce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_name', full_name='dota.CClientMsg_CustomGameEventBounce.event_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='dota.CClientMsg_CustomGameEventBounce.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_index', full_name='dota.CClientMsg_CustomGameEventBounce.player_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=184,
)


_CCLIENTMSG_CLIENTUIEVENT = _descriptor.Descriptor(
  name='CClientMsg_ClientUIEvent',
  full_name='dota.CClientMsg_ClientUIEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='dota.CClientMsg_ClientUIEvent.event', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ent_ehandle', full_name='dota.CClientMsg_ClientUIEvent.ent_ehandle', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_ehandle', full_name='dota.CClientMsg_ClientUIEvent.client_ehandle', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data1', full_name='dota.CClientMsg_ClientUIEvent.data1', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data2', full_name='dota.CClientMsg_ClientUIEvent.data2', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=349,
)


_CCLIENTMSG_DEVPALETTEVISIBILITYCHANGEDEVENT = _descriptor.Descriptor(
  name='CClientMsg_DevPaletteVisibilityChangedEvent',
  full_name='dota.CClientMsg_DevPaletteVisibilityChangedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='visible', full_name='dota.CClientMsg_DevPaletteVisibilityChangedEvent.visible', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=413,
)


_CCLIENTMSG_WORLDUICONTROLLERHASPANELCHANGEDEVENT = _descriptor.Descriptor(
  name='CClientMsg_WorldUIControllerHasPanelChangedEvent',
  full_name='dota.CClientMsg_WorldUIControllerHasPanelChangedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_panel', full_name='dota.CClientMsg_WorldUIControllerHasPanelChangedEvent.has_panel', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_ehandle', full_name='dota.CClientMsg_WorldUIControllerHasPanelChangedEvent.client_ehandle', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='literal_hand_type', full_name='dota.CClientMsg_WorldUIControllerHasPanelChangedEvent.literal_hand_type', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=535,
)


_CCLIENTMSG_ROTATEANCHOR = _descriptor.Descriptor(
  name='CClientMsg_RotateAnchor',
  full_name='dota.CClientMsg_RotateAnchor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angle', full_name='dota.CClientMsg_RotateAnchor.angle', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=577,
)

_CCLIENTMSG_CLIENTUIEVENT.fields_by_name['event'].enum_type = _ECLIENTUIEVENT
DESCRIPTOR.message_types_by_name['CClientMsg_CustomGameEvent'] = _CCLIENTMSG_CUSTOMGAMEEVENT
DESCRIPTOR.message_types_by_name['CClientMsg_CustomGameEventBounce'] = _CCLIENTMSG_CUSTOMGAMEEVENTBOUNCE
DESCRIPTOR.message_types_by_name['CClientMsg_ClientUIEvent'] = _CCLIENTMSG_CLIENTUIEVENT
DESCRIPTOR.message_types_by_name['CClientMsg_DevPaletteVisibilityChangedEvent'] = _CCLIENTMSG_DEVPALETTEVISIBILITYCHANGEDEVENT
DESCRIPTOR.message_types_by_name['CClientMsg_WorldUIControllerHasPanelChangedEvent'] = _CCLIENTMSG_WORLDUICONTROLLERHASPANELCHANGEDEVENT
DESCRIPTOR.message_types_by_name['CClientMsg_RotateAnchor'] = _CCLIENTMSG_ROTATEANCHOR
DESCRIPTOR.enum_types_by_name['EBaseClientMessages'] = _EBASECLIENTMESSAGES
DESCRIPTOR.enum_types_by_name['EClientUIEvent'] = _ECLIENTUIEVENT

CClientMsg_CustomGameEvent = _reflection.GeneratedProtocolMessageType('CClientMsg_CustomGameEvent', (_message.Message,), dict(
  DESCRIPTOR = _CCLIENTMSG_CUSTOMGAMEEVENT,
  __module__ = 'clientmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CClientMsg_CustomGameEvent)
  ))
_sym_db.RegisterMessage(CClientMsg_CustomGameEvent)

CClientMsg_CustomGameEventBounce = _reflection.GeneratedProtocolMessageType('CClientMsg_CustomGameEventBounce', (_message.Message,), dict(
  DESCRIPTOR = _CCLIENTMSG_CUSTOMGAMEEVENTBOUNCE,
  __module__ = 'clientmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CClientMsg_CustomGameEventBounce)
  ))
_sym_db.RegisterMessage(CClientMsg_CustomGameEventBounce)

CClientMsg_ClientUIEvent = _reflection.GeneratedProtocolMessageType('CClientMsg_ClientUIEvent', (_message.Message,), dict(
  DESCRIPTOR = _CCLIENTMSG_CLIENTUIEVENT,
  __module__ = 'clientmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CClientMsg_ClientUIEvent)
  ))
_sym_db.RegisterMessage(CClientMsg_ClientUIEvent)

CClientMsg_DevPaletteVisibilityChangedEvent = _reflection.GeneratedProtocolMessageType('CClientMsg_DevPaletteVisibilityChangedEvent', (_message.Message,), dict(
  DESCRIPTOR = _CCLIENTMSG_DEVPALETTEVISIBILITYCHANGEDEVENT,
  __module__ = 'clientmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CClientMsg_DevPaletteVisibilityChangedEvent)
  ))
_sym_db.RegisterMessage(CClientMsg_DevPaletteVisibilityChangedEvent)

CClientMsg_WorldUIControllerHasPanelChangedEvent = _reflection.GeneratedProtocolMessageType('CClientMsg_WorldUIControllerHasPanelChangedEvent', (_message.Message,), dict(
  DESCRIPTOR = _CCLIENTMSG_WORLDUICONTROLLERHASPANELCHANGEDEVENT,
  __module__ = 'clientmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CClientMsg_WorldUIControllerHasPanelChangedEvent)
  ))
_sym_db.RegisterMessage(CClientMsg_WorldUIControllerHasPanelChangedEvent)

CClientMsg_RotateAnchor = _reflection.GeneratedProtocolMessageType('CClientMsg_RotateAnchor', (_message.Message,), dict(
  DESCRIPTOR = _CCLIENTMSG_ROTATEANCHOR,
  __module__ = 'clientmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CClientMsg_RotateAnchor)
  ))
_sym_db.RegisterMessage(CClientMsg_RotateAnchor)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001\200\001\000'))
# @@protoc_insertion_point(module_scope)
