# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connectionless_netmessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dotaproto import netmessages_pb2 as netmessages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='connectionless_netmessages.proto',
  package='dota',
  syntax='proto2',
  serialized_pb=_b('\n connectionless_netmessages.proto\x12\x04\x64ota\x1a\x11netmessages.proto\"\xa2\x02\n\x13\x43\x32S_CONNECT_Message\x12\x14\n\x0chost_version\x18\x01 \x01(\r\x12\x15\n\rauth_protocol\x18\x02 \x01(\r\x12\x18\n\x10\x63hallenge_number\x18\x03 \x01(\r\x12\x1a\n\x12reservation_cookie\x18\x04 \x01(\x06\x12\x14\n\x0clow_violence\x18\x05 \x01(\x08\x12\x1a\n\x12\x65ncrypted_password\x18\x06 \x01(\x0c\x12\x36\n\x0csplitplayers\x18\x07 \x03(\x0b\x32 .dota.CCLCMsg_SplitPlayerConnect\x12\x12\n\nauth_steam\x18\x08 \x01(\x0c\x12\x19\n\x11\x63hallenge_context\x18\t \x01(\t\x12\x0f\n\x07use_snp\x18\n \x01(\x11\"=\n\x16\x43\x32S_CONNECTION_Message\x12\x12\n\naddon_name\x18\x01 \x01(\t\x12\x0f\n\x07use_snp\x18\x02 \x01(\x08\x42\x03\x80\x01\x00')
  ,
  dependencies=[netmessages__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_C2S_CONNECT_MESSAGE = _descriptor.Descriptor(
  name='C2S_CONNECT_Message',
  full_name='dota.C2S_CONNECT_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host_version', full_name='dota.C2S_CONNECT_Message.host_version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_protocol', full_name='dota.C2S_CONNECT_Message.auth_protocol', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='challenge_number', full_name='dota.C2S_CONNECT_Message.challenge_number', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reservation_cookie', full_name='dota.C2S_CONNECT_Message.reservation_cookie', index=3,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='low_violence', full_name='dota.C2S_CONNECT_Message.low_violence', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encrypted_password', full_name='dota.C2S_CONNECT_Message.encrypted_password', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='splitplayers', full_name='dota.C2S_CONNECT_Message.splitplayers', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_steam', full_name='dota.C2S_CONNECT_Message.auth_steam', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='challenge_context', full_name='dota.C2S_CONNECT_Message.challenge_context', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_snp', full_name='dota.C2S_CONNECT_Message.use_snp', index=9,
      number=10, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=352,
)


_C2S_CONNECTION_MESSAGE = _descriptor.Descriptor(
  name='C2S_CONNECTION_Message',
  full_name='dota.C2S_CONNECTION_Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='addon_name', full_name='dota.C2S_CONNECTION_Message.addon_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_snp', full_name='dota.C2S_CONNECTION_Message.use_snp', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=415,
)

_C2S_CONNECT_MESSAGE.fields_by_name['splitplayers'].message_type = netmessages__pb2._CCLCMSG_SPLITPLAYERCONNECT
DESCRIPTOR.message_types_by_name['C2S_CONNECT_Message'] = _C2S_CONNECT_MESSAGE
DESCRIPTOR.message_types_by_name['C2S_CONNECTION_Message'] = _C2S_CONNECTION_MESSAGE

C2S_CONNECT_Message = _reflection.GeneratedProtocolMessageType('C2S_CONNECT_Message', (_message.Message,), dict(
  DESCRIPTOR = _C2S_CONNECT_MESSAGE,
  __module__ = 'connectionless_netmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.C2S_CONNECT_Message)
  ))
_sym_db.RegisterMessage(C2S_CONNECT_Message)

C2S_CONNECTION_Message = _reflection.GeneratedProtocolMessageType('C2S_CONNECTION_Message', (_message.Message,), dict(
  DESCRIPTOR = _C2S_CONNECTION_MESSAGE,
  __module__ = 'connectionless_netmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.C2S_CONNECTION_Message)
  ))
_sym_db.RegisterMessage(C2S_CONNECTION_Message)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\200\001\000'))
# @@protoc_insertion_point(module_scope)
