# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dota_broadcastmessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dota_broadcastmessages.proto',
  package='dota',
  syntax='proto2',
  serialized_pb=_b('\n\x1c\x64ota_broadcastmessages.proto\x12\x04\x64ota\"e\n\x11\x43\x44OTABroadcastMsg\x12\x43\n\x04type\x18\x01 \x02(\x0e\x32\x1c.dota.EDotaBroadcastMessages:\x17\x44OTA_BM_LANLobbyRequest\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\"#\n!CDOTABroadcastMsg_LANLobbyRequest\"\xc6\x02\n\x1f\x43\x44OTABroadcastMsg_LANLobbyReply\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x15\n\rtournament_id\x18\x02 \x01(\r\x12\x1a\n\x12tournament_game_id\x18\x03 \x01(\r\x12\x43\n\x07members\x18\x04 \x03(\x0b\x32\x32.dota.CDOTABroadcastMsg_LANLobbyReply.CLobbyMember\x12\x19\n\x11requires_pass_key\x18\x05 \x01(\x08\x12\x19\n\x11leader_account_id\x18\x06 \x01(\r\x12\x11\n\tgame_mode\x18\x07 \x01(\r\x12\x0c\n\x04name\x18\x08 \x01(\t\x12\x0f\n\x07players\x18\t \x01(\r\x1a\x37\n\x0c\x43LobbyMember\x12\x12\n\naccount_id\x18\x01 \x01(\r\x12\x13\n\x0bplayer_name\x18\x02 \x01(\t*P\n\x16\x45\x44otaBroadcastMessages\x12\x1b\n\x17\x44OTA_BM_LANLobbyRequest\x10\x01\x12\x19\n\x15\x44OTA_BM_LANLobbyReply\x10\x02\x42\x05H\x01\x80\x01\x00')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EDOTABROADCASTMESSAGES = _descriptor.EnumDescriptor(
  name='EDotaBroadcastMessages',
  full_name='dota.EDotaBroadcastMessages',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOTA_BM_LANLobbyRequest', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOTA_BM_LANLobbyReply', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=507,
  serialized_end=587,
)
_sym_db.RegisterEnumDescriptor(_EDOTABROADCASTMESSAGES)

EDotaBroadcastMessages = enum_type_wrapper.EnumTypeWrapper(_EDOTABROADCASTMESSAGES)
DOTA_BM_LANLobbyRequest = 1
DOTA_BM_LANLobbyReply = 2



_CDOTABROADCASTMSG = _descriptor.Descriptor(
  name='CDOTABroadcastMsg',
  full_name='dota.CDOTABroadcastMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='dota.CDOTABroadcastMsg.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='dota.CDOTABroadcastMsg.msg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=139,
)


_CDOTABROADCASTMSG_LANLOBBYREQUEST = _descriptor.Descriptor(
  name='CDOTABroadcastMsg_LANLobbyRequest',
  full_name='dota.CDOTABroadcastMsg_LANLobbyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=176,
)


_CDOTABROADCASTMSG_LANLOBBYREPLY_CLOBBYMEMBER = _descriptor.Descriptor(
  name='CLobbyMember',
  full_name='dota.CDOTABroadcastMsg_LANLobbyReply.CLobbyMember',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.CLobbyMember.account_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_name', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.CLobbyMember.player_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=505,
)

_CDOTABROADCASTMSG_LANLOBBYREPLY = _descriptor.Descriptor(
  name='CDOTABroadcastMsg_LANLobbyReply',
  full_name='dota.CDOTABroadcastMsg_LANLobbyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tournament_id', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.tournament_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tournament_game_id', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.tournament_game_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='members', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.members', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requires_pass_key', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.requires_pass_key', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leader_account_id', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.leader_account_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_mode', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.game_mode', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players', full_name='dota.CDOTABroadcastMsg_LANLobbyReply.players', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CDOTABROADCASTMSG_LANLOBBYREPLY_CLOBBYMEMBER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=505,
)

_CDOTABROADCASTMSG.fields_by_name['type'].enum_type = _EDOTABROADCASTMESSAGES
_CDOTABROADCASTMSG_LANLOBBYREPLY_CLOBBYMEMBER.containing_type = _CDOTABROADCASTMSG_LANLOBBYREPLY
_CDOTABROADCASTMSG_LANLOBBYREPLY.fields_by_name['members'].message_type = _CDOTABROADCASTMSG_LANLOBBYREPLY_CLOBBYMEMBER
DESCRIPTOR.message_types_by_name['CDOTABroadcastMsg'] = _CDOTABROADCASTMSG
DESCRIPTOR.message_types_by_name['CDOTABroadcastMsg_LANLobbyRequest'] = _CDOTABROADCASTMSG_LANLOBBYREQUEST
DESCRIPTOR.message_types_by_name['CDOTABroadcastMsg_LANLobbyReply'] = _CDOTABROADCASTMSG_LANLOBBYREPLY
DESCRIPTOR.enum_types_by_name['EDotaBroadcastMessages'] = _EDOTABROADCASTMESSAGES

CDOTABroadcastMsg = _reflection.GeneratedProtocolMessageType('CDOTABroadcastMsg', (_message.Message,), dict(
  DESCRIPTOR = _CDOTABROADCASTMSG,
  __module__ = 'dota_broadcastmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CDOTABroadcastMsg)
  ))
_sym_db.RegisterMessage(CDOTABroadcastMsg)

CDOTABroadcastMsg_LANLobbyRequest = _reflection.GeneratedProtocolMessageType('CDOTABroadcastMsg_LANLobbyRequest', (_message.Message,), dict(
  DESCRIPTOR = _CDOTABROADCASTMSG_LANLOBBYREQUEST,
  __module__ = 'dota_broadcastmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CDOTABroadcastMsg_LANLobbyRequest)
  ))
_sym_db.RegisterMessage(CDOTABroadcastMsg_LANLobbyRequest)

CDOTABroadcastMsg_LANLobbyReply = _reflection.GeneratedProtocolMessageType('CDOTABroadcastMsg_LANLobbyReply', (_message.Message,), dict(

  CLobbyMember = _reflection.GeneratedProtocolMessageType('CLobbyMember', (_message.Message,), dict(
    DESCRIPTOR = _CDOTABROADCASTMSG_LANLOBBYREPLY_CLOBBYMEMBER,
    __module__ = 'dota_broadcastmessages_pb2'
    # @@protoc_insertion_point(class_scope:dota.CDOTABroadcastMsg_LANLobbyReply.CLobbyMember)
    ))
  ,
  DESCRIPTOR = _CDOTABROADCASTMSG_LANLOBBYREPLY,
  __module__ = 'dota_broadcastmessages_pb2'
  # @@protoc_insertion_point(class_scope:dota.CDOTABroadcastMsg_LANLobbyReply)
  ))
_sym_db.RegisterMessage(CDOTABroadcastMsg_LANLobbyReply)
_sym_db.RegisterMessage(CDOTABroadcastMsg_LANLobbyReply.CLobbyMember)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001\200\001\000'))
# @@protoc_insertion_point(module_scope)
