# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dota_modifiers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dotaproto import networkbasetypes_pb2 as networkbasetypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dota_modifiers.proto',
  package='dota',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x64ota_modifiers.proto\x12\x04\x64ota\x1a\x16networkbasetypes.proto\"\xa2\x06\n\x1b\x43\x44OTAModifierBuffTableEntry\x12S\n\nentry_type\x18\x01 \x02(\x0e\x32\x1e.dota.DOTA_MODIFIER_ENTRY_TYPE:\x1f\x44OTA_MODIFIER_ENTRY_TYPE_ACTIVE\x12\x0e\n\x06parent\x18\x02 \x02(\x05\x12\r\n\x05index\x18\x03 \x02(\x05\x12\x12\n\nserial_num\x18\x04 \x02(\x05\x12\x16\n\x0emodifier_class\x18\x05 \x01(\x05\x12\x15\n\rability_level\x18\x06 \x01(\x05\x12\x13\n\x0bstack_count\x18\x07 \x01(\x05\x12\x15\n\rcreation_time\x18\x08 \x01(\x02\x12\x14\n\x08\x64uration\x18\t \x01(\x02:\x02-1\x12\x0e\n\x06\x63\x61ster\x18\n \x01(\x05\x12\x0f\n\x07\x61\x62ility\x18\x0b \x01(\x05\x12\r\n\x05\x61rmor\x18\x0c \x01(\x05\x12\x11\n\tfade_time\x18\r \x01(\x02\x12\x0e\n\x06subtle\x18\x0e \x01(\x08\x12\x14\n\x0c\x63hannel_time\x18\x0f \x01(\x02\x12!\n\x07v_start\x18\x10 \x01(\x0b\x32\x10.dota.CMsgVector\x12\x1f\n\x05v_end\x18\x11 \x01(\x0b\x32\x10.dota.CMsgVector\x12\x1a\n\x12portal_loop_appear\x18\x12 \x01(\t\x12\x1d\n\x15portal_loop_disappear\x18\x13 \x01(\t\x12\x18\n\x10hero_loop_appear\x18\x14 \x01(\t\x12\x1b\n\x13hero_loop_disappear\x18\x15 \x01(\t\x12\x16\n\x0emovement_speed\x18\x16 \x01(\x05\x12\x0c\n\x04\x61ura\x18\x17 \x01(\x08\x12\x10\n\x08\x61\x63tivity\x18\x18 \x01(\x05\x12\x0e\n\x06\x64\x61mage\x18\x19 \x01(\x05\x12\r\n\x05range\x18\x1a \x01(\x05\x12\x19\n\x11\x64\x64_modifier_index\x18\x1b \x01(\x05\x12\x15\n\rdd_ability_id\x18\x1c \x01(\x05\x12\x16\n\x0eillusion_label\x18\x1d \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x1e \x01(\x08\x12\x12\n\nplayer_ids\x18\x1f \x01(\t\x12\x10\n\x08lua_name\x18  \x01(\t\x12\x14\n\x0c\x61ttack_speed\x18! \x01(\x05\"I\n\x15\x43\x44OTALuaModifierEntry\x12\x15\n\rmodifier_type\x18\x01 \x02(\x05\x12\x19\n\x11modifier_filename\x18\x02 \x02(\t*e\n\x18\x44OTA_MODIFIER_ENTRY_TYPE\x12#\n\x1f\x44OTA_MODIFIER_ENTRY_TYPE_ACTIVE\x10\x01\x12$\n DOTA_MODIFIER_ENTRY_TYPE_REMOVED\x10\x02\x42\x05H\x01\x80\x01\x00')
  ,
  dependencies=[networkbasetypes__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DOTA_MODIFIER_ENTRY_TYPE = _descriptor.EnumDescriptor(
  name='DOTA_MODIFIER_ENTRY_TYPE',
  full_name='dota.DOTA_MODIFIER_ENTRY_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOTA_MODIFIER_ENTRY_TYPE_ACTIVE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOTA_MODIFIER_ENTRY_TYPE_REMOVED', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=934,
  serialized_end=1035,
)
_sym_db.RegisterEnumDescriptor(_DOTA_MODIFIER_ENTRY_TYPE)

DOTA_MODIFIER_ENTRY_TYPE = enum_type_wrapper.EnumTypeWrapper(_DOTA_MODIFIER_ENTRY_TYPE)
DOTA_MODIFIER_ENTRY_TYPE_ACTIVE = 1
DOTA_MODIFIER_ENTRY_TYPE_REMOVED = 2



_CDOTAMODIFIERBUFFTABLEENTRY = _descriptor.Descriptor(
  name='CDOTAModifierBuffTableEntry',
  full_name='dota.CDOTAModifierBuffTableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry_type', full_name='dota.CDOTAModifierBuffTableEntry.entry_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parent', full_name='dota.CDOTAModifierBuffTableEntry.parent', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='dota.CDOTAModifierBuffTableEntry.index', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serial_num', full_name='dota.CDOTAModifierBuffTableEntry.serial_num', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modifier_class', full_name='dota.CDOTAModifierBuffTableEntry.modifier_class', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ability_level', full_name='dota.CDOTAModifierBuffTableEntry.ability_level', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack_count', full_name='dota.CDOTAModifierBuffTableEntry.stack_count', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='dota.CDOTAModifierBuffTableEntry.creation_time', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='dota.CDOTAModifierBuffTableEntry.duration', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='caster', full_name='dota.CDOTAModifierBuffTableEntry.caster', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ability', full_name='dota.CDOTAModifierBuffTableEntry.ability', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='armor', full_name='dota.CDOTAModifierBuffTableEntry.armor', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fade_time', full_name='dota.CDOTAModifierBuffTableEntry.fade_time', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subtle', full_name='dota.CDOTAModifierBuffTableEntry.subtle', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel_time', full_name='dota.CDOTAModifierBuffTableEntry.channel_time', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v_start', full_name='dota.CDOTAModifierBuffTableEntry.v_start', index=15,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v_end', full_name='dota.CDOTAModifierBuffTableEntry.v_end', index=16,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='portal_loop_appear', full_name='dota.CDOTAModifierBuffTableEntry.portal_loop_appear', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='portal_loop_disappear', full_name='dota.CDOTAModifierBuffTableEntry.portal_loop_disappear', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero_loop_appear', full_name='dota.CDOTAModifierBuffTableEntry.hero_loop_appear', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero_loop_disappear', full_name='dota.CDOTAModifierBuffTableEntry.hero_loop_disappear', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='movement_speed', full_name='dota.CDOTAModifierBuffTableEntry.movement_speed', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aura', full_name='dota.CDOTAModifierBuffTableEntry.aura', index=22,
      number=23, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activity', full_name='dota.CDOTAModifierBuffTableEntry.activity', index=23,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='damage', full_name='dota.CDOTAModifierBuffTableEntry.damage', index=24,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range', full_name='dota.CDOTAModifierBuffTableEntry.range', index=25,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dd_modifier_index', full_name='dota.CDOTAModifierBuffTableEntry.dd_modifier_index', index=26,
      number=27, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dd_ability_id', full_name='dota.CDOTAModifierBuffTableEntry.dd_ability_id', index=27,
      number=28, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='illusion_label', full_name='dota.CDOTAModifierBuffTableEntry.illusion_label', index=28,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active', full_name='dota.CDOTAModifierBuffTableEntry.active', index=29,
      number=30, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_ids', full_name='dota.CDOTAModifierBuffTableEntry.player_ids', index=30,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lua_name', full_name='dota.CDOTAModifierBuffTableEntry.lua_name', index=31,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_speed', full_name='dota.CDOTAModifierBuffTableEntry.attack_speed', index=32,
      number=33, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=857,
)


_CDOTALUAMODIFIERENTRY = _descriptor.Descriptor(
  name='CDOTALuaModifierEntry',
  full_name='dota.CDOTALuaModifierEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modifier_type', full_name='dota.CDOTALuaModifierEntry.modifier_type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modifier_filename', full_name='dota.CDOTALuaModifierEntry.modifier_filename', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=859,
  serialized_end=932,
)

_CDOTAMODIFIERBUFFTABLEENTRY.fields_by_name['entry_type'].enum_type = _DOTA_MODIFIER_ENTRY_TYPE
_CDOTAMODIFIERBUFFTABLEENTRY.fields_by_name['v_start'].message_type = networkbasetypes__pb2._CMSGVECTOR
_CDOTAMODIFIERBUFFTABLEENTRY.fields_by_name['v_end'].message_type = networkbasetypes__pb2._CMSGVECTOR
DESCRIPTOR.message_types_by_name['CDOTAModifierBuffTableEntry'] = _CDOTAMODIFIERBUFFTABLEENTRY
DESCRIPTOR.message_types_by_name['CDOTALuaModifierEntry'] = _CDOTALUAMODIFIERENTRY
DESCRIPTOR.enum_types_by_name['DOTA_MODIFIER_ENTRY_TYPE'] = _DOTA_MODIFIER_ENTRY_TYPE

CDOTAModifierBuffTableEntry = _reflection.GeneratedProtocolMessageType('CDOTAModifierBuffTableEntry', (_message.Message,), dict(
  DESCRIPTOR = _CDOTAMODIFIERBUFFTABLEENTRY,
  __module__ = 'dota_modifiers_pb2'
  # @@protoc_insertion_point(class_scope:dota.CDOTAModifierBuffTableEntry)
  ))
_sym_db.RegisterMessage(CDOTAModifierBuffTableEntry)

CDOTALuaModifierEntry = _reflection.GeneratedProtocolMessageType('CDOTALuaModifierEntry', (_message.Message,), dict(
  DESCRIPTOR = _CDOTALUAMODIFIERENTRY,
  __module__ = 'dota_modifiers_pb2'
  # @@protoc_insertion_point(class_scope:dota.CDOTALuaModifierEntry)
  ))
_sym_db.RegisterMessage(CDOTALuaModifierEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001\200\001\000'))
# @@protoc_insertion_point(module_scope)
